### ISSUE TITLE
mqtt.log shows error org.apache.rocketmq.client.exception.MQBrokerException: CODE: 17 how to fix it?

### ISSUE THREAD

**Issue by islongshiyu** [apache/rocketmq-mqtt#165]
+ Version: v1.0.0

the mqtt.log shows too much error logs:

```shell
2022-10-23 16:02:47:096 ERROR [LmqOffsetStoreManager] 
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 17  DESC: Topic %retry%1666770984090% not exist! BROKER: 192.168.50.22:10911
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.updateConsumerOffset(MQClientAPIImpl.java:1011)
        at org.apache.rocketmq.mqtt.ds.store.LmqOffsetStoreManager.save(LmqOffsetStoreManager.java:91)
        at org.apache.rocketmq.mqtt.cs.session.loop.SessionLoopImpl.persistOffset(SessionLoopImpl.java:540)
        at org.apache.rocketmq.mqtt.cs.session.loop.SessionLoopImpl.persistAllOffset(SessionLoopImpl.java:526)
        at org.apache.rocketmq.mqtt.cs.session.loop.SessionLoopImpl.lambda$init$0(SessionLoopImpl.java:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```
How to fix it?

**Comment by DongyuanPan** [comment]
FYI https://github.com/apache/rocketmq-mqtt/issues/150
