### ISSUE TITLE
"this.upstreamHookManager" is null

### ISSUE THREAD

**Issue by khalidjshaikh** [apache/rocketmq-mqtt#189]
Thoughts?

```
cat /etc/issue
Ubuntu 22.04.2 LTS \n \l
```

```
java --version
openjdk 20 2023-03-21
OpenJDK Runtime Environment Corretto-20.0.0.36.1 (build 20+36-FR)
OpenJDK 64-Bit Server VM Corretto-20.0.0.36.1 (build 20+36-FR, mixed mode, sharing)
```

## RocketMQ is running
```
bin/mqnamesrv
The Name Server boot success. serializeType=JSON
```
```
bin/mqbroker
The broker[ubuntu-6b5777999d-hzskq, 100.96.3.12:10911] boot success. serializeType=JSON
```
```
root@ubuntu-6b5777999d-hzskq:/# netstat -an | grep LISTEN
tcp6       0      0 :::10912                :::*                    LISTEN     
tcp6       0      0 :::10909                :::*                    LISTEN     
tcp6       0      0 :::10911                :::*                    LISTEN     
tcp6       0      0 :::9876                 :::*                    LISTEN   
```
## RocketMQ-MQTT both main and develop branch
```
root@ubuntu-6b5777999d-hzskq:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT# ls bin
meta.sh  mqtt.sh  runserver.sh
root@ubuntu-6b5777999d-hzskq:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT# bash bin/mqtt.sh start
+ '[' -z '' ']'
+ PRG=bin/mqtt.sh
+ '[' -h bin/mqtt.sh ']'
++ pwd
+ saveddir=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT
++ dirname bin/mqtt.sh
+ ROCKETMQ_MQTT_HOME=bin/..
++ cd bin/..
++ pwd
+ ROCKETMQ_MQTT_HOME=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT
+ cd /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT
+ export ROCKETMQ_MQTT_HOME
+ BASEDIR=/root
+ mkdir -p /root/logs
+ mainClass=org.apache.rocketmq.mqtt.cs.starter.Startup
+ case "$1" in
+ startup start
++ ps aux
++ grep org.apache.rocketmq.mqtt.cs.starter.Startup
++ grep -v grep
++ awk '{print $2}'
+ pid=
+ '[' '!' -z '' ']'
+ nohup sh /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/runserver.sh org.apache.rocketmq.mqtt.cs.starter.Startup start
root@ubuntu-6b5777999d-hzskq:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT# /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/runserver.sh org.apache.rocketmq.mqtt.cs.starter.Startup start
+ '[' '!' -e /root/.sdkman/candidates/java/current/bin/java ']'
+ '[' '!' -e /root/.sdkman/candidates/java/current/bin/java ']'
+ '[' '!' -e /root/.sdkman/candidates/java/current/bin/java ']'
+ export JAVA=/root/.sdkman/candidates/java/current/bin/java
+ JAVA=/root/.sdkman/candidates/java/current/bin/java
++ dirname /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/runserver.sh
+ export BASE_DIR=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/..
+ BASE_DIR=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/..
+ export CLASSPATH=.:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf:conf:lib/mqtt-cs-1.0.2-SNAPSHOT.jar:lib/spring-core-4.3.16.RELEASE.jar:lib/spring-aop-4.3.16.RELEASE.jar:lib/spring-beans-4.3.16.RELEASE.jar:lib/spring-context-4.3.16.RELEASE.jar:lib/commons-logging-1.2.jar:lib/spring-expression-4.3.16.RELEASE.jar:lib/netty-all-4.1.43.Final.jar:lib/rocketmq-remoting-4.9.3.jar:lib/rocketmq-common-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar:lib/rocketmq-logging-4.9.3.jar:lib/slf4j-api-1.7.15.jar:lib/mqtt-ds-1.0.2-SNAPSHOT.jar:lib/commons-lang3-3.7.jar:lib/rocketmq-client-4.9.3.jar:lib/mqtt-exporter-1.0.2-SNAPSHOT.jar:lib/fastjson-1.2.83.jar:lib/jraft-core-1.3.11.jar:lib/protobuf-java-3.8.0.jar:lib/caffeine-2.6.2.jar:lib/rocketmq-tools-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar
+ CLASSPATH=.:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf:conf:lib/mqtt-cs-1.0.2-SNAPSHOT.jar:lib/spring-core-4.3.16.RELEASE.jar:lib/spring-aop-4.3.16.RELEASE.jar:lib/spring-beans-4.3.16.RELEASE.jar:lib/spring-context-4.3.16.RELEASE.jar:lib/commons-logging-1.2.jar:lib/spring-expression-4.3.16.RELEASE.jar:lib/netty-all-4.1.43.Final.jar:lib/rocketmq-remoting-4.9.3.jar:lib/rocketmq-common-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar:lib/rocketmq-logging-4.9.3.jar:lib/slf4j-api-1.7.15.jar:lib/mqtt-ds-1.0.2-SNAPSHOT.jar:lib/commons-lang3-3.7.jar:lib/rocketmq-client-4.9.3.jar:lib/mqtt-exporter-1.0.2-SNAPSHOT.jar:lib/fastjson-1.2.83.jar:lib/jraft-core-1.3.11.jar:lib/protobuf-java-3.8.0.jar:lib/caffeine-2.6.2.jar:lib/rocketmq-tools-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar
+ DIR_SIZE_IN_MB=600
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow'
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages'
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages -cp /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../lib'
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages -cp /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../lib '
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages -cp /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../lib  -cp .:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf:conf:lib/mqtt-cs-1.0.2-SNAPSHOT.jar:lib/spring-core-4.3.16.RELEASE.jar:lib/spring-aop-4.3.16.RELEASE.jar:lib/spring-beans-4.3.16.RELEASE.jar:lib/spring-context-4.3.16.RELEASE.jar:lib/commons-logging-1.2.jar:lib/spring-expression-4.3.16.RELEASE.jar:lib/netty-all-4.1.43.Final.jar:lib/rocketmq-remoting-4.9.3.jar:lib/rocketmq-common-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar:lib/rocketmq-logging-4.9.3.jar:lib/slf4j-api-1.7.15.jar:lib/mqtt-ds-1.0.2-SNAPSHOT.jar:lib/commons-lang3-3.7.jar:lib/rocketmq-client-4.9.3.jar:lib/mqtt-exporter-1.0.2-SNAPSHOT.jar:lib/fastjson-1.2.83.jar:lib/jraft-core-1.3.11.jar:lib/protobuf-java-3.8.0.jar:lib/caffeine-2.6.2.jar:lib/rocketmq-tools-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar'
+ JAVA_OPT=' -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages -cp /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../lib  -cp .:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf:conf:lib/mqtt-cs-1.0.2-SNAPSHOT.jar:lib/spring-core-4.3.16.RELEASE.jar:lib/spring-aop-4.3.16.RELEASE.jar:lib/spring-beans-4.3.16.RELEASE.jar:lib/spring-context-4.3.16.RELEASE.jar:lib/commons-logging-1.2.jar:lib/spring-expression-4.3.16.RELEASE.jar:lib/netty-all-4.1.43.Final.jar:lib/rocketmq-remoting-4.9.3.jar:lib/rocketmq-common-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar:lib/rocketmq-logging-4.9.3.jar:lib/slf4j-api-1.7.15.jar:lib/mqtt-ds-1.0.2-SNAPSHOT.jar:lib/commons-lang3-3.7.jar:lib/rocketmq-client-4.9.3.jar:lib/mqtt-exporter-1.0.2-SNAPSHOT.jar:lib/fastjson-1.2.83.jar:lib/jraft-core-1.3.11.jar:lib/protobuf-java-3.8.0.jar:lib/caffeine-2.6.2.jar:lib/rocketmq-tools-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar -Dlogback.configurationFile=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf/logback.xml'
+ /root/.sdkman/candidates/java/current/bin/java -XX:-OmitStackTraceInFastThrow -XX:-UseLargePages -cp /rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../lib -cp .:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf:conf:lib/mqtt-cs-1.0.2-SNAPSHOT.jar:lib/spring-core-4.3.16.RELEASE.jar:lib/spring-aop-4.3.16.RELEASE.jar:lib/spring-beans-4.3.16.RELEASE.jar:lib/spring-context-4.3.16.RELEASE.jar:lib/commons-logging-1.2.jar:lib/spring-expression-4.3.16.RELEASE.jar:lib/netty-all-4.1.43.Final.jar:lib/rocketmq-remoting-4.9.3.jar:lib/rocketmq-common-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar:lib/rocketmq-logging-4.9.3.jar:lib/slf4j-api-1.7.15.jar:lib/mqtt-ds-1.0.2-SNAPSHOT.jar:lib/commons-lang3-3.7.jar:lib/rocketmq-client-4.9.3.jar:lib/mqtt-exporter-1.0.2-SNAPSHOT.jar:lib/fastjson-1.2.83.jar:lib/jraft-core-1.3.11.jar:lib/protobuf-java-3.8.0.jar:lib/caffeine-2.6.2.jar:lib/rocketmq-tools-4.9.3.jar:lib/mqtt-common-1.0.2-SNAPSHOT.jar -Dlogback.configurationFile=/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT/bin/../conf/logback.xml org.apache.rocketmq.mqtt.cs.starter.Startup start
Apr 13, 2023 6:36:48 AM org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@6433a2: startup date [Thu Apr 13 06:36:48 GMT 2023]; root of context hierarchy
Apr 13, 2023 6:36:48 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from class path resource [spring.xml]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 13, 2023 6:36:49 AM org.springframework.context.support.ClassPathXmlApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authManager' defined in class path resource [spring.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "org.apache.rocketmq.mqtt.common.hook.UpstreamHookManager.addHook(int, org.apache.rocketmq.mqtt.common.hook.UpstreamHook)" because "this.upstreamHookManager" is null
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authManager' defined in class path resource [spring.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "org.apache.rocketmq.mqtt.common.hook.UpstreamHookManager.addHook(int, org.apache.rocketmq.mqtt.common.hook.UpstreamHook)" because "this.upstreamHookManager" is null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.apache.rocketmq.mqtt.cs.starter.Startup.main(Startup.java:30)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.rocketmq.mqtt.common.hook.UpstreamHookManager.addHook(int, org.apache.rocketmq.mqtt.common.hook.UpstreamHook)" because "this.upstreamHookManager" is null
	at org.apache.rocketmq.mqtt.ds.auth.AuthManagerSample.register(AuthManagerSample.java:69)
	at org.apache.rocketmq.mqtt.ds.auth.AuthManagerSample.init(AuthManagerSample.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1759)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1696)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 12 more
root@ubuntu-6b5777999d-hzskq:/rocketmq-mqtt2/distribution/target/rocketmq-mqtt-1.0.2-SNAPSHOT/rocketmq-mqtt-1.0.2-SNAPSHOT# 
```

**Comment by pingww** [comment]
It may be related to the jdk version, try jdk11 ？
