### ISSUE TITLE
JSON解析报错一直写日志每天20G以上

### ISSUE THREAD

**Issue by JaynLau** [apache/rocketmq-mqtt#307]
通过docker部署的rocketmq-5.2.0+rocketmq-mqtt-1.0.1

一直重复报下面的JSON解析错误日志：
```
2024-07-18 14:16:19:333 ERROR [QueueCache] 
com.alibaba.fastjson.JSONException: unclosed.str
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:657)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.parseMap(MapDeserializer.java:133)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:69)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:43)
        at com.alibaba.fastjson.parser.deserializer.ContextObjectDeserializer.deserialze(ContextObjectDeserializer.java:9)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:705)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:362)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:276)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.toLmqMessage(LmqQueueStoreManager.java:154)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.toLmqPullResult(LmqQueueStoreManager.java:326)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.access$300(LmqQueueStoreManager.java:76)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager$3.onSuccess(LmqQueueStoreManager.java:234)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager$4.onSuccess(LmqQueueStoreManager.java:356)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:761)
        at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:54)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:320)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:826)
2024-07-18 14:16:19:333 ERROR [LmqQueueStoreManager] 
com.alibaba.fastjson.JSONException: unclosed.str
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSymbol(JSONLexerBase.java:657)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.parseMap(MapDeserializer.java:133)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:69)
        at com.alibaba.fastjson.parser.deserializer.MapDeserializer.deserialze(MapDeserializer.java:43)
        at com.alibaba.fastjson.parser.deserializer.ContextObjectDeserializer.deserialze(ContextObjectDeserializer.java:9)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:705)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:394)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:362)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:276)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.toLmqMessage(LmqQueueStoreManager.java:154)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.toLmqPullResult(LmqQueueStoreManager.java:326)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager.access$300(LmqQueueStoreManager.java:76)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager$3.onSuccess(LmqQueueStoreManager.java:234)
        at org.apache.rocketmq.mqtt.ds.store.LmqQueueStoreManager$4.onSuccess(LmqQueueStoreManager.java:356)
        at org.apache.rocketmq.client.impl.MQClientAPIImpl$2.operationComplete(MQClientAPIImpl.java:761)
        at org.apache.rocketmq.remoting.netty.ResponseFuture.executeInvokeCallback(ResponseFuture.java:54)
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract$2.run(NettyRemotingAbstract.java:320)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:826)
```

**Comment by DongyuanPan** [comment]
you can try RocketMQ version: >= 4.9.3 and <= 5.1.4 and rocketmq-mqtt develop branch
