### ISSUE TITLE
Concurrent unit test failure problem

### ISSUE THREAD

**Issue by tianliuliu** [apache/rocketmq-mqtt#75]
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.025 sec <<< FAILURE!
testDoHandlerSuccess(org.apache.rocketmq.mqtt.cs.test.protocol.mqtt.handler.TestMqttConnectHandler)  Time elapsed: 1.018 sec  <<< FAILURE!
Wanted but not invoked:
channel.writeAndFlush(
    <any io.netty.handler.codec.mqtt.MqttConnAckMessage>
);
-> at org.apache.rocketmq.mqtt.cs.test.protocol.mqtt.handler.TestMqttConnectHandler.testDoHandlerSuccess(TestMqttConnectHandler.java:131)
However, there were exactly 5 interactions with this mock:
channel.attr(I);
-> at org.apache.rocketmq.mqtt.cs.channel.ChannelInfo.getInfo(ChannelInfo.java:245)
channel.attr(I);
-> at org.apache.rocketmq.mqtt.cs.channel.ChannelInfo.getInfo(ChannelInfo.java:245)
channel.attr(I);
-> at org.apache.rocketmq.mqtt.cs.channel.ChannelInfo.getInfo(ChannelInfo.java:245)
channel.attr(I);
-> at org.apache.rocketmq.mqtt.cs.channel.ChannelInfo.getInfo(ChannelInfo.java:245)
channel.attr(I);
-> at org.apache.rocketmq.mqtt.cs.channel.ChannelInfo.getInfo(ChannelInfo.java:245)
  at org.apache.rocketmq.mqtt.cs.test.protocol.mqtt.handler.TestMqttConnectHandler.testDoHandlerSuccess(TestMqttConnectHandler.java:131)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:44)
  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:74)
  at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:80)
  at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
  at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by YxAc** [comment]
@tianliuliu thanks for your time, i will check them more carefully.

**Comment by tianliuliu** [comment]
> @tianliuliu thanks for your time, i will check them more carefully.

you are welcome,  enen
